name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
        
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: |
          heroku git:remote -a polydan-1f195a22e2e0
          git push heroku HEAD:main 